// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"FeiraVed/todolist/controller"
	"FeiraVed/todolist/repository"
	"FeiraVed/todolist/service"
	"FeiraVed/todolist/view"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedView() *view.TodolistViewImpl {
	todolistRepositoryImpl := repository.NewTodolistRepository()
	todolistServiceImpl := service.NewTodolistService(todolistRepositoryImpl)
	todolistControllerImpl := controller.NewTodolistController(todolistServiceImpl)
	todolistViewImpl := view.NewTodolistView(todolistControllerImpl)
	return todolistViewImpl
}

// injector.go:

var todolistSet = wire.NewSet(repository.NewTodolistRepository, wire.Bind(new(repository.TodolistRepository), new(*repository.TodolistRepositoryImpl)), service.NewTodolistService, wire.Bind(new(service.TodolistService), new(*service.TodolistServiceImpl)), controller.NewTodolistController, wire.Bind(new(controller.TodolistController), new(*controller.TodolistControllerImpl)))
